/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.zhu.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.zhu.entity.Hotspot;
import com.zhu.service.HotSpotService;

/**
 * MyEclipse Struts Creation date: 04-08-2015
 * 
 * XDoclet definition:
 * 
 * @struts.action scope="request" validate="true"
 */
public class IndexAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	@Override
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HotSpotService hotspotService = new HotSpotService();
		List<Hotspot> hotspotlist = hotspotService.getHotSpot();
		request.setAttribute("hotspot", hotspotlist);
		return mapping.findForward("list");
	}
}